# Generated by Django 4.1.1 on 2022-09-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='About_yourself',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
