# Generated by Django 4.1.1 on 2022-09-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_resume_about_yourself'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='Specialization',
            field=models.CharField(choices=[('Web_development', 'Web_development'), ('Marketing', 'Marketing'), ('Journalism', 'journalism'), ('civil engineer', 'civil engineer'), ('recruiting', 'recruiting'), ('architect', 'architect'), ('Data engineer', 'Data engineer'), ('Teaching', 'Teaching')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='Work_experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
