# Generated by Django 4.1.1 on 2022-09-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_resume_specialization_resume_work_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='linkdin_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
